name: Build
on:
  push:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build app
    runs-on: ubuntu-24.04

    steps:
      - name: Clone repo
        uses: actions/checkout@main

      - name: Set up JDK
        uses: actions/setup-java@main
        with:
          java-version: 17
          distribution: adopt

      - name: Setup Android SDK
        run: |
          ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager "build-tools;29.0.3"

      - name: Set up gradle
        uses: gradle/actions/setup-gradle@main

      - name: Build app
        run: ./gradlew assembleDevPreview

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Mihon
          path: app/build/outputs/apk/*
